variables:

  ANDROID_COMPILE_SDK: "30"
  ANDROID_BUILD_TOOLS: "30.0.3"
  ANDROID_SDK_TOOLS: "6514223"

before_script:
  - echo "sdk.dir=${ANDROID_HOME}" >> local.properties
  - echo "ndk.dir=${ANDROID_NDK_HOME}" >> local.properties
  - chmod +x ./gradlew

buildDebug:
  interruptible: true
  stage: build
  script:
    - ./gradlew clean assembleDebug --stacktrace
  artifacts:
    paths:
      - nunchuk-app/build/outputs/

